#!/bin/bash

# must be run as root.
if [[ $(whoami) != "root" ]]; then
	echo script must be run as root.
	exit 1
fi

# pigz must be installed.
dpkg-query -l pigz &>/dev/null
if [[ $? != 0 ]]; then
	echo pigz must be installed.
	exit 1
fi

# pv must be installed.
dpkg-query -l pv &>/dev/null
if [[ $? != 0 ]]; then
	echo pv must be installed.
	exit 1
fi

###
# Loading config
###

echo Loading config...

source "$(dirname "$0")/config"

###
# Check whether there are updates
###

echo Checking for updates...

apt update

if [[ $(apt list --upgradable | wc -l) == 1 ]]; then
	echo "Nothing to be done."
	exit 0
fi

###
# Archive the filesystem
###

echo Archiving the filesystem...

dd if="$DEVICE" bs=64M | pv | pigz --best -p $PROCESSES | dd of="$FILEPATH"

###
# Upgrade the system.
###

echo Upgrading installed packages...

apt upgrade -y

echo Done!
